[ClassVersion("1.0.0"), FriendlyName("CMAssetIntelligencePoint")]
class DSC_CMAssetIntelligencePoint: OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Write, Description("Specifies the Site Server to install or configure the role on. If the role is already installed on another server this setting will be ignored.")] String SiteServerName;
    [Write, Description("Specifies the path to a System Center Online authentication certificate (.pfx) file. If used, this must be in UNC format. Local paths are not allowed. Mutually exclusive with the RemoveCertificate parameter.")] String CertificateFile;
    [Write, Description("Specifies whether the installed asset intelligence role is enabled or disabled.")] Boolean Enable;
    [Write, Description("Specifies whether to synchronize the asset intelligence catalog.")] Boolean EnableSynchronization;
    [Write, Description("Specifies whether to remove a configured certificate file. Mutually exclusive with the CertificateFile Parameter.")] Boolean RemoveCertificate;
    [Write, Description("Specifies whether the asset intelligence synchronization point is present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Specifies the start date and start time for the synchronization schedule Month/Day/Year, example 1/1/2020 02:00.")] String Start;
    [Write, Description("Specifies the schedule type for the synchronization schedule."), ValueMap{"MonthlyByDay","MonthlyByWeek","Weekly","Days","None"}, Values{"MonthlyByDay","MonthlyByWeek","Weekly","Days","None"}] String ScheduleType;
    [Write, Description("Specifies how often the ScheduleType is run.")] UInt32 RecurInterval;
    [Write, Description("Specifies week order for MonthlyByWeek schedule type."), ValueMap{"First","Second","Third","Fourth","Last"}, Values{"First","Second","Third","Fourth","Last"}] String MonthlyWeekOrder;
    [Write, Description("Specifies the day of week name for MonthlyByWeek and Weekly schedules."), ValueMap{"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"}, Values{"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"}] String DayOfWeek;
    [Write, Description("Specifies the day number for MonthlyByDay schedules.")] UInt32 DayOfMonth;
};
