[ClassVersion("1.0.0"), FriendlyName("CMClientStatusSettings")]
class DSC_CMClientStatusSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Write, Description("Specifies the data collection interval for client policy client monitoring activities.")] UInt32 ClientPolicyDays;
    [Write, Description("Specifies the data collection interval for heartbeat discovery client monitoring activities.")] UInt32 HeartbeatDiscoveryDays;
    [Write, Description("Specifies the data collection interval for software inventory client monitoring activities.")] UInt32 SoftwareInventoryDays;
    [Write, Description("Specifies the data collection interval for hardware inventory client monitoring activities.")] UInt32 HardwareInventoryDays;
    [Write, Description("Specifies the data collection interval for status message client monitoring activities.")] UInt32 StatusMessageDays;
    [Write, Description("Specifies the data collection interval for status history cleanup client monitoring activities.")] UInt32 HistoryCleanupDays;
};
