[ClassVersion("1.0.0"), FriendlyName("CMHeartbeatDiscovery")]
class DSC_CMHeartbeatDiscovery : OMI_BaseResource
{
    [Key, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Required, Description("Specifies the enablement of the heartbeat discovery method.")] Boolean Enabled;
    [Write, Description("Specifies the recur interval of days, hours"),ValueMap{"Days","Hours"},Values{"Days","Hours"}] String ScheduleInterval;
    [Write, Description("Specifies how often the recur interval is run. If hours are specified the max value is 23. Anything over 23 will result in 23 to be set. If days are specified the max value is 31. Anything over 31 will result in 31 to be set.")] UInt32 ScheduleCount;
};
