[ClassVersion("1.0.0"), FriendlyName("CMClientSettingsSoftwareDeployment")]
class DSC_CMClientSettingsSoftwareDeployment : OMI_BaseResource
{
    [Key, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Key, Description("Specifies which client settings policy to modify.")] String ClientSettingName;
    [Write, Description("Specifies the start date and start time for the software deployment schedule Month/Day/Year, example 1/1/2020 02:00.")] String Start;
    [Write, Description("Specifies the schedule type for the software deployment schedule."), ValueMap{"MonthlyByDay","MonthlyByWeek","Weekly","Days","Hours","Minutes","None"}, Values{"MonthlyByDay","MonthlyByWeek","Weekly","Days","Hours","Minutes","None"}] String ScheduleType;
    [Write, Description("Specifies how often the ScheduleType is run.")] UInt32 RecurInterval;
    [Write, Description("Specifies week order for MonthlyByWeek schedule type."), ValueMap{"First","Second","Third","Fourth","Last"}, Values{"First","Second","Third","Fourth","Last"}] String MonthlyWeekOrder;
    [Write, Description("Specifies the day of week name for MonthlyByWeek and Weekly schedules."), ValueMap{"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"}, Values{"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"}] String DayOfWeek;
    [Write, Description("Specifies the day number for MonthlyByDay schedules.")] UInt32 DayOfMonth;
    [Read, Description("Specifies if the client settings policy exists.")] String ClientSettingStatus;
    [Read, Description("Specifies the type of client policy setting.")] String ClientType;
};
