[ClassVersion("1.0.0"), FriendlyName("CMDistributionPointGroup")]
class DSC_CMDistributionPointGroup : OMI_BaseResource
{
    [Key, Description("Specifies the Distribution Point Group name.")] String DistributionPointGroup;
    [Required, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Write, Description("Specifies an array of distribution points to match to the distribution point group.")] String DistributionPoints[];
    [Write, Description("Specifies an array of distribution points to add to the distribution point group.")] String DistributionPointsToInclude[];
    [Write, Description("Specifies an array of distribution points to remove from the distribution point group.")] String DistributionPointsToExclude[];
    [Write, Description("Specifies whether the distribution point group is present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
