[ClassVersion("1.0.0"), FriendlyName("CMDistributionGroup")]
class DSC_CMDistributionGroup : OMI_BaseResource
{
    [Key, Description("Specifies the Distribution Group name.")] String DistributionGroup;
    [Required, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Write, Description("Specifies an array of Distribution Points to match to the Distribution Group.")] String DistributionPoints[];
    [Write, Description("Specifies an array of Distribution Points to add to the Distribution Group.")] String DistributionPointsToInclude[];
    [Write, Description("Specifies an array of Distribution Points to remove from the Distribution Group.")] String DistributionPointsToExclude[];
    [Write, Description("Specifies an array of Security Scopes to match to the Distribution Group.")] String SecurityScopes[];
    [Write, Description("Specifies an array of Security Scopes to add to the Distribution Group.")] String SecurityScopesToInclude[];
    [Write, Description("Specifies an array of Security Scopes to remove from the Distribution Group.")] String SecurityScopesToExclude[];
    [Write, Description("Specifies whether the Distribution Group is present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
