[ClassVersion("1.0.0"), FriendlyName("CMReportingServicePoint")]
class DSC_CMReportingServicePoint: OMI_BaseResource
{
    [Key, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Key, Description("Specifies the Site Server to install or configure the role on.")] String SiteServerName;
    [Write, Description("Specifies the name of the Configuration Manager database that you want to use as the data source for reports from Microsoft SQL Server Reporting Services.")] String DatabaseName;
    [Write, Description("Specifies the name of the Configuration Manager database server that you want to use as the data source for reports from Microsoft SQL Server Reporting Services.")] String DatabaseServerName;
    [Write, Description("Specifies the name of the report folder on the report server.")] String FolderName;
    [Write, Description("Specifies the name of an instance of Microsoft SQL Server Reporting Services.")] String ReportServerInstance;
    [Write, Description("Specifies a user name for an account that Configuration Manager uses to connect with Microsoft SQL Server Reporting Services and that gives this user access to the site database.")] String UserName;
    [Write, Description("Specifies whether the reporting service point is present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
