[ClassVersion("1.0.0"), FriendlyName("CMSoftwareUpdatePoint")]
class DSC_CMSoftwareUpdatePoint: OMI_BaseResource
{
    [Key, Description("Specifies the SiteCode for the Configuration Manager site.")] String SiteCode;
    [Required, Description("Specifies the Site Server to install or configure the role on.")] String SiteServerName;
    [Write, Description("Indicates that the software update point allows anonymous access. Mutually exclusive with WSUSAccessAccount.")] Boolean AnonymousWSUSAccess;
    [Write, Description("Specifies the type of the client connection"), ValueMap{"Internet","Intranet","InternetAndIntranet"}, Values{"Internet","Intranet","InternetAndIntranet"}] String ClientConnectionType;
    [Write, Description("Specifies if a cloud gateway is to be used for the software update point.")] Boolean EnableCloudGateway;
    [Write, Description("Indicates whether a software update point uses the proxy configured for the site system server.")] Boolean UseProxy;
    [Write, Description("Indicates whether an auto deployment rule can use a proxy.")] Boolean UseProxyForAutoDeploymentRule;
    [Write, Description("Specifies an account used to connect to the WSUS server.When not used, specify the AnonymousWSUSAccess parameter.")] String WSUSAccessAccount;
    [Write, Description("Specifies a port to use for unsecured access to the WSUS server.")] UInt32 WsusIisPort;
    [Write, Description("Specifies whether the software update point uses SSL to connect to the WSUS server.")] UInt32 WsusIisSslPort;
    [Write, Description("Specifies whether the software update point uses SSL to connect to the WSUS server.")] Boolean WsusSsl;
    [Write, Description("Specifies whether the software update point is present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
