#
# Module manifest for module 'ConfigMgrCBDsc'
#
# Generated by: Microsoft Corporation
#
# Generated on: 05/21/2019
#

@{
    # Version number of this module.
    ModuleVersion = '0.0.1'

    # ID used to uniquely identify this module
    GUID = '89e420e1-77ff-4a79-afc3-15532da94912'

    # Author of this module
    Author = 'Microsoft Corporation'

    # Company or vendor of this module
    CompanyName = 'Microsoft Corporation'

    # Copyright statement for this module
    Copyright = '(c) 2019 Microsoft Corporation. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'This module includes DSC resources that simplify administration of Configuration Manager CB'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '4.0'

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = '4.0'

    # DSC resources to export from this module
    DscResourcesToExport = @('ClientSettings','CMAccounts')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.

            Tags = @('ConfigMgrCBDsc', 'ClientSettings','CMAccounts')

            # A URL to the main website for this project.

            ProjectUri = 'DSC/Modules'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
